
BEGIN TRY
    BEGIN TRANSACTION;

    IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'Username')
    BEGIN
        ALTER TABLE Users ALTER COLUMN Username NVARCHAR(100) NULL;
    END

    IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'Role')
    BEGIN
        ALTER TABLE Users ALTER COLUMN Role VARCHAR(20) NULL;
    END

    IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'Status')
    BEGIN
        ALTER TABLE Users ALTER COLUMN Status NVARCHAR(50) NULL;
    END

    IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'PhoneNumber')
    BEGIN
        ALTER TABLE Users ALTER COLUMN PhoneNumber VARCHAR(15) NULL;
    END

    IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'Address')
        ALTER TABLE Users ALTER COLUMN Address NVARCHAR(255) NULL;

    IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'City')
        ALTER TABLE Users ALTER COLUMN City NVARCHAR(100) NULL;

    IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'AvatarUrl')
        ALTER TABLE Users ALTER COLUMN AvatarUrl VARCHAR(500) NULL;

    COMMIT TRANSACTION;

END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;
END CATCH;
GO
