BEGIN TRY
    BEGIN TRANSACTION;

    IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'Username')
    BEGIN
        ALTER TABLE Users ALTER COLUMN Username NVARCHAR(100) NULL;
    END

    IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'Role')
    BEGIN
        ALTER TABLE Users ALTER COLUMN Role VARCHAR(20) NULL;
    END

    IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'Status')
    BEGIN
        ALTER TABLE Users ALTER COLUMN Status NVARCHAR(50) NULL;
    END

    IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'PhoneNumber')
    BEGIN
        ALTER TABLE Users ALTER COLUMN PhoneNumber VARCHAR(15) NULL;
    END

    IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'Address')
        ALTER TABLE Users ALTER COLUMN Address NVARCHAR(255) NULL;

    IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'City')
        ALTER TABLE Users ALTER COLUMN City NVARCHAR(100) NULL;

    IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'AvatarUrl')
        ALTER TABLE Users ALTER COLUMN AvatarUrl VARCHAR(500) NULL;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'TrangThai')
    BEGIN
        ALTER TABLE Users ADD TrangThai INT DEFAULT 1;
    END

    EXEC sp_executesql N'UPDATE Users SET TrangThai = 1';

    COMMIT TRANSACTION;

END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;
END CATCH;
GO

INSERT INTO Users (FullName, Email, PasswordHash) 
VALUES (N'Huỳnh Bích Trân', 'tran@gmail.com', '123456');

SELECT TOP 5 * FROM Users